### ISSUE TITLE
Tutorial please?

### ISSUE THREAD

**Issue by DesperateKidNeedsHelp** [mattanger/ckb-next#179]
Can anyone show me a quick tutorial on how to build ckb.app with BUILD.md? In BUILD.md it asks me to build ckb.pro in Qt5, but it doesn't work.

**Comment by frickler24** [comment]
On what system? Mac? Linux? What linux distro? What does not work? Did you install all prereqs? ...
Always the same questions. If you want an answer which is helpful for you, please learn to ask.

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 |  Mac |  It said to build it with Cmd + B and it will put ckb.app in the directory. I didn't see any changes at all and it came with a command that would search the app if it the process went well, but it didn't find it.  |  Prereqs???  |

**Comment by tatokis** [comment]
Try this 
https://github.com/mattanger/ckb-next/releases/download/v0.2.8/ckb-v0.2.8.pkg

**Comment by fleischie** [comment]
I guess we can also add an Install/Build from Source section to the Wiki, if we restructure the docs.

I think the pre-packaged binary is a good step in the right direction, though.

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 Same result as quickinstall. When I open it shows ckb for a second and quits, leaving me to deal with the _Enter_ key spamming me.

**Comment by frickler24** [comment]
@DesperateKidNeedsHelp I think you have more than one installation on your system.
To Prereqs: Did you proper install ALL prerequisites mentioned in the README.md for macOS?
Are there updates available for Xcode or QT5?
Have there been errors (no warnings) in your last run of quickinstall?
Did you install it via launchctl (answered two times "y" in install procedure)?

What do you get if you run `find / -name quickinstall -print 2>/dev/null`?
And what is shown with `pgrep ckb`?
What services are running `sudo launchctl list`?

What timestamp has your daemon `ls -l /Library/LaunchDaemons/com.ckb.daemon.plist`? 
Is this date congruent to your last run of quickinstall?

Did you try the package mentioned by Tatokis above? 
Did you deinstall ckb before you installed the link from Tatokis?
What results did you get?

Because we do not have access to your system, you should create a picture with us, what is wrong with your system. This is the only way we can help and that is the only way to make the time for it.

**Comment by DesperateKidNeedsHelp** [comment]
![screen shot 2017-05-07 at 1 20 03 pm](https://cloud.githubusercontent.com/assets/27321024/25783301/f6b4698e-3327-11e7-8943-2bebdbd5244a.png)
@frickler24 
The original comment was all mangled when I posted it, so I had to screenshot of what I wrote.

**Comment by frickler24** [comment]
I wonder why you do not get info from the lauchctl command, because it should show at least your daemon (which exists with normal timestamp). But I do not have a mac, so it is a bit fuzzy for me.
Please show me the listing of your directory, where ckb-next starts `cd <somewhere>/ckb-next; ls -l`.
In this ckb-next start directory do a recompile with  `yes | quickinstall > /tmp/logfile 2>&1` 
and send me /tmp/logfile you created.

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 (Quick note) Ok, tatokis before sent me a new file called, ckb-next-testing, which was supposed to maybe would work instead of the original ckb-next. I know very little about the technical things about computers. So if you could bear with me and explain the steps a little more clear for me to understand that would be so helpful. Thanks.

**Comment by frickler24** [comment]
OK, step by step.
Open a terminal. As I know macOS, you should start in your home directory.
copy& paste `pwd ; whoami`
please post the result of these two commands.
It should look like this:
```
lutz@Mainfrix ~ $ pwd ; whoami
/home/lutz
lutz
```
Tip: If you post some lines, mark them and click on the \<\> logo, they are posted exactly as they are - the mangling mentioned before does not occur.

Then copy&paste the following line and post the output again: `find / -name quickinstall -print | less`
We are searching, how many installation files you have and where they are.
Because you will get several error messages, you must refresh the output of less. Type a "b" into the window and paste what you see now (usefule lines only. Leave less by typing "q").
As you wrote some posts before: If really nothing is printed out here, you don't have cloned ckb-next.
So something should be written by this command.
If something useful comes with this command, lets' try the next ones:
`ls -l $(find / -name quickinstall -print | sed "s#quickinstall##") > /tmp/log1.txt`
and `cat $(find / -name quickinstall -print | sed "s#quickinstall##")/VERSION > /tmp/versions.txt`
should bring two files in /tmp (use `ls -ls /tmp` to check).
Please post these two files.

**Comment by DesperateKidNeedsHelp** [comment]
```
TiMaKoVs-iMac:~ TiMaKoV$ pwd ; whoami
/Users/TiMaKoV
TiMaKoV
```
I'm not getting ANY error messages, only "Permission denied."
But do you mean this? `/Users/TiMaKoV/Desktop/ckb-next-testing/quickinstall`

I used `ls -ls /tmp` to check and I received this, `8 lrwxr-xr-x@ 1 root  wheel  11 Jan 27 19:01 /tmp -> private/tmp`.
I don't see anything relating to two files you mentioned unless you want the output for the 2 commands..

@frickler24

**Comment by frickler24** [comment]
OK, then go in this directory and let's have a look what is in there:
`cd /Users/TiMaKoV/Desktop/ckb-next-testing ; ls -l ; cat VERSION`
Then please compile everything:
`yes | quickinstall`
This will ask you for your password (it contains a sudo-command); please answer it
Then paste all what happened.
What is your ckb client doing now?

**Comment by frickler24** [comment]
@fleischie or @tatokis A question to our mac users: How should he install the 0.2.8.pkg file? Is it like a .deb-file starting automatically after download? Put it into /tmp and open it with some tool? Open the link with a tool?

**Comment by tatokis** [comment]
I don't use Mac. Only thing I know is that you just double click it and it gets installed.

**Comment by ghost** [comment]
@frickler24 
macOS package is like an NSIS installer.

**Comment by frickler24** [comment]
OK, thanks, We will see what @DesperateKidNeedsHelp brings out now

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 Sorry, how do you compile `cd /Users/TiMaKoV/Desktop/ckb-next-testing ; ls -l ; cat VERSION`? Do you use `yes | quickinstall`?

Here's the `cd /Users/TiMaKoV/Desktop/ckb-next-testing ; ls -l ; cat VERSION` output anyways.

```
TiMaKoVs-iMac:~ TiMaKoV$ cd /Users/TiMaKoV/Desktop/ckb-next-testing ; ls -l ; cat VERSION
total 424
-rwxr-xr-x@  1 TiMaKoV  staff   3489 Apr 28 02:39 BUILD.md
-rwxr-xr-x@  1 TiMaKoV  staff  19357 Apr 28 02:39 DAEMON.md
-rwxr-xr-x@  1 TiMaKoV  staff   3490 Apr 28 02:39 FIRMWARE
-rwxr-xr-x@  1 TiMaKoV  staff  18027 Apr 28 02:39 LICENSE
-rw-r--r--   1 TiMaKoV  staff  66609 May  7 13:05 Makefile
-rwxr-xr-x@  1 TiMaKoV  staff  15735 Apr 28 02:39 README.md
-rwxr-xr-x@  1 TiMaKoV  staff    433 Apr 28 02:39 ROADMAP.md
-rwxr-xr-x@  1 TiMaKoV  staff     12 Apr 28 02:39 VERSION
-rwxr-xr-x@  1 TiMaKoV  staff   1179 Apr 28 02:39 ckb-dev-detect
drwxr-xr-x   3 TiMaKoV  staff    102 May  2 21:40 ckb.app
-rwxr-xr-x@  1 TiMaKoV  staff    457 Apr 28 02:39 ckb.pro
-rw-r--r--   1 TiMaKoV  staff  48160 May  6 17:24 ckb.pro.user
drwxr-xr-x@  7 TiMaKoV  staff    238 May  2 21:36 osx
-rwxr-xr-x@  1 TiMaKoV  staff   1113 Apr 28 02:39 qmake-auto
-rwxr-xr-x@  1 TiMaKoV  staff   8277 Apr 28 02:39 quickinstall
drwxr-xr-x@  6 TiMaKoV  staff    204 Apr 28 02:39 service
drwxr-xr-x@ 12 TiMaKoV  staff    408 Apr 28 02:39 src
drwxr-xr-x@  4 TiMaKoV  staff    136 Apr 28 02:39 usr
beta-v0.2.7
```
I don't think the Makefile is supposed to be there. I think I might've created it by accident or probably not.

**Comment by frickler24** [comment]
Yes, complete compilation and installation is done with 
`cd /Users/TiMaKoV/Desktop/ckb-next-testing ; yes | quickinstall`.

After compilation and installation, please post the output from quickinstall.

Currently you have Version v0.2.7, so here we do not see the content of the link, tatokis sent you.
Because 28th of April is a bit too old, you really should download the [package](https://github.com/mattanger/ckb-next/releases/download/v0.2.8/ckb-v0.2.8.pkg). If it asks you for a place to save, say `/Users/TiMaKoV/Desktop` or short "~".
Then double click on the package at your desktop.
What's going on? Different behavior of your ckb?

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 Wow, what bad timing! I can't continue trying to fix ckb-next anymore. My mac started getting incredibly slow and laggy these past few days. Now, it doesn't even start. Sorry, I'm going to have to resume this later until my mac is fixed or snaps out of it. (This is posted on a other device.. Just so you know.)      

Sorry :(

**Comment by DesperateKidNeedsHelp** [comment]
@frickler24 @tatokis @light2yellow @fleischie Ey, I fixed my computer, but.... I will no longer try to get ckb on my Mac. When I finally booted the computer back up I instantly went to check viruses or threats. I found ckb stuff. Sorry I don't want to take another risk. I'm so so so so sorry for wasting your time. After all it is just a keyboard, lighting doesn't make it better.
