### ISSUE TITLE
Dragging makes the mouse stuck m65 rgb

### ISSUE THREAD

**Issue by boyknight53** [mattanger/ckb-next#217]
whenever i try to drag files or anything else the mouse goes to the middle of the screen and gets stuck
https://youtu.be/ZQ0VQ4wszic

**Comment by Zach443** [comment]
I have this too, and it happens not only when I try to drag something but also every 3rd click or so. Same mouse, I'm running Sierra.

**Comment by smallyes** [comment]
Same here. My mouse gets stuck every time I click it.

**Comment by AlfaceVerde** [comment]
some problem here, when i drag something my mouse jump to top left

**Comment by Frankenmint** [comment]
Yeah this happens on OSX for me too. I've figured out that it's happening because you have Displays Have Separate spaces checked.  With this enabled, my mouse will hang in the same origin location 0,0 (upper left corner of my screen).  You can unplug then plug your mouse back in to get drag/drop functionality, but when this happens it is no longer recognized by the software so macros don't work.  

![Imgur](https://i.imgur.com/ZQVCcIu.png)
Why would we have checked this box?  
Well, I liked the idea of having separate spaces so that I could maximize the window on one screen and not black out my other screen.  When I try that feature it breaks support of the mouse and does the behavior described here. I know there are a ton of open issues but if @mattanger has any ideas for how to help fix this we're all ears to help you.

**Comment by Ravenslofty** [comment]
Funnily enough, @mattanger isn't around anymore. I think @fleischie might be most able to fix this, but we shall see.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/23
