### ISSUE TITLE
K70 Detected as K70R

### ISSUE THREAD

**Issue by ghost** [mattanger/ckb-next#224]
This is a minor problem, I may be able to fix it and do a pull request, but my K70 is detected as a K70R. This should not be displayed as a K70R.

**Comment by tatokis** [comment]
What does this mean, exactly?

**Comment by ghost** [comment]
It means that K70 might be detected as K70 Rapidfire.

Please post the output of `ckb-dev-detect` from the source tree root (this is a shell script), logs from `ckb-daemon` (by `systemctl status ckb-daemon`) and a screenshot of `ckb` GUI.

**Comment by ghost** [comment]
K70R is detected on both Linux and Mac. So it seems to nothing to do with the Linux Kernel. I was just making sure. The keybinding and everything works. The layout of the keyboard is the same as what I have.

I do not have SystemCtl on MacOS. I recently switched to MacOS from Linux.
http://www.corsair.com/en-us/corsair-gaming-k70-mechanical-gaming-keyboard-cherry-mx-brown-ch-9000116-na

**Comment by rijujohnx** [comment]
This is what happens to my Corsair K70 vengeance too.  Two issues bug me a lot.  
1. Shift key and multi select don't work after a reboot.  I had to reinstall the ckb driver every time to make it work.
2. The keys don't respond at times.  I have to manually disconnect/reconnect the USB connection.

**Comment by SethBarberee** [comment]
Can you post the output of 'ckb-dev-detect'?

**Comment by rijujohnx** [comment]
@SethBarberee `OS Version:
ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73
USB Devices:
            Corsair K70R Gaming Keyboard:
              Product ID: 0x1b09
              Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
              Version: 1.09
              Speed: Up to 12 Mb/sec
              Manufacturer: Corsair
              Location ID: 0x14140000 / 9
              Current Available (mA): 500
              Current Required (mA): 500`

**Comment by ghost** [comment]
@Aeirex try `cmake` branch or pre-built package from #281 and post the output of `/var/log/ckb-next-daemon.log`.

@rijujohnx removing your comments as they are not on the topic of this issue. Instead of poking random threads consider searching for existing ones and subscribing, but if you won't find one, open a new issue describing your problem according to the template.

**Comment by rijujohnx** [comment]
Any updates on this issue?

**Comment by tatokis** [comment]
Can someone explain to me what the actual issue is? It's impossible for the k70 to be detected as a rapidfire. Additionally, where do you see this detection? All the k70 devices are grouped, so ultimately it doesn't matter.

**Comment by ghost** [comment]
@rijujohnx 

If you want this problem solved,
> Please post the output of `ckb-dev-detect` from the source tree root (this is a shell script), logs from `ckb-daemon` (by `systemctl status ckb-daemon`) and a screenshot of `ckb` GUI.

**Comment by rijujohnx** [comment]
@tatokis   The issue is Corsair Vengeance K70 keyboard is being detected as K70R ( K70 Rapidfire, as per the GUI).  

However, my main issue isn't that it's detected as K70R but the fact that sometime after waking up the mac from sleep the keyboard fails to register keys and becomes unresponsive and then a sudden burst of the keys get registered.  I typically unplug the keyboard and replug and it works fine for sometime.  The issues usually gets resolved if I remove and reinstall ckb-next and randomly appears in future after sleep-wakes.  I thought it might be tied to K70R but not sure.  If I recall K70R uses a different MCU.

Even I thought so. Looking at the header source files it seems the K70 should be detected as P_K70_NRGB.

`ckb-dev-detect - Mon Oct  2 13:50:23 EDT 2017

Kernel: Darwin mbp-XXXXXXXX 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

OS Version:
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29

USB Devices:
            Corsair K70R Gaming Keyboard:
              Product ID: 0x1b09
              Vendor ID: 0x1b1c  (CORSAIR MEMORY INC.)
              Version: 1.09
              Speed: Up to 12 Mb/sec
              Manufacturer: Corsair
              Location ID: 0x14140000 / 12
              Current Available (mA): 500
              Current Required (mA): 500
              Extra Operating Current (mA): 0
            Lenovo USB Optical Mouse:
`
GUI screenshot
https://imgur.com/4poCnR2

@light2yellow  How can i get those logs on mac?

**Comment by rijujohnx** [comment]
I used the launchctl commands to get few more logging info.  Below is the extract from /var/log/ckb.log  /var/log/ckb.err.log is blank

ckb: Corsair RGB driver v0.2.8
[I] Root controller ready at /var/run/ckb0
[I] Connecting Corsair K70R Gaming Keyboard at /var/run/ckb1
[I] Registering EventTap for modifier keys.
[I] Starting input thread for /var/run/ckb1
[I] Setup finished for /var/run/ckb1

**Comment by tatokis** [comment]
Yeah, not much can be done about that.
The device calls itself "K70R", and the daemon just copies and displays it.

**Comment by AaronBottegal** [comment]
Working on fixing the K70 Calculator issue on Linux. Vengence K70 shares the same product code. Nothing to do, ever.
