### ISSUE TITLE
Corsair Scimitar Pro Firmware

### ISSUE THREAD

**Issue by SethBarberee** [mattanger/ckb-next#229]
CKB thinks that it is a regular Scimitar (v. 2.03) so it is trying to upgrade it. Scimitar Pro has a recent firmware of v1.10 according to CUE. Everything besides that for the Scimitar Pro works as expected on ckb-next.

**Comment by tatokis** [comment]
The Scimitar Pro is not in the firmware file https://github.com/mattanger/ckb-next/blob/master/FIRMWARE 
but even if it was, there's #220 that fixes this exact issue.

I suppose if you really wanted, you could try that PR, and since ckb would no longer be able to find the right device, it should not prompt for an update at all.
If you do try it, please do report any success in the PR thread.
