### ISSUE TITLE
Scimitar RGB firmware out of date (now 2.04)

### ISSUE THREAD

**Issue by OscarBarrett** [mattanger/ckb-next#246]
https://www3.corsair.com/software/HID/Scimitar.zip now contains `SCIMITAR_APP_V204.bin`, as such the hash in FIRMWARE no longer matches.

**Comment by ghost** [comment]
Can you try to upgrade your gear manually through ckb-next GUI? The only reason of not adding it is the lack of testing. So, if you happen to own Scimitar RGB, you'll help a lot by upgrading it through ckb-next and reporting what got broken.

**Comment by OscarBarrett** [comment]
I have upgraded manually and haven't noticed any issues so far. Although the upgrade was from 1.06 😅 

I'll comment again once I've spent some more time using the new firmware.

**Comment by OscarBarrett** [comment]
I haven't noticed any new problems since the upgrade. General use, lighting and keybinds are all working fine.

**Comment by ghost** [comment]
Unfortunately I lost my access to ckb-next key pair due to unreachable private key and revocation file for it which was signed to provide such access, so I am not able to update the file unless I re-request the access. I will need some time to study this topic and figure out a better path to persistent and reliable setup with portable offline private key which is always reachable. Unassigning.
