### ISSUE TITLE
ckb-next 0.2.8 No devices connected for Corsair Strafe No RGB Mac Os X El Capitan

### ISSUE THREAD

**Issue by Mazhaa** [mattanger/ckb-next#356]
I have the Corsair Strafe no Rgb keyboard and ckb-next 0.2.8 show me "No devices connected" when I plug my keyboard . Can someone help me ?

**Comment by ghost** [comment]
Output of `launchctl list | grep ckb-daemon`?

**Comment by Mazhaa** [comment]
```
-	0	com.ckb.ckb
1293	0	com.apple.xpc.launchd.oneshot.0x1000000b.ckb
```

There are this two things when I type launchctl list on terminal

**Comment by ghost** [comment]
Sorry, I forgot to answer.

First of all, it looks like you did `launchctl list | grep ckb` instead of the above. Secondly, [newer] Strafe non-RGB was added after 0.2.8, so build the program from source. Thirdly, I probably forgot to mention `sudo`, I don't remember whether `launchd` requires sudo to view `root` jobs. So, in case it still isn't detected after being built manually, execute `sudo launchctl list | grep ckb-daemon` (and post it here). In case there will be no output, execute `sudo launchctl load -w /Library/LaunchDaemons/com.ckb.daemon.plist`.

**Comment by monsonjeremy** [comment]
I've noticed that this issue happens after restarting my macbook. It works fine when i reinstall CKB but as soon as i perform a restart i lose it :(

**Comment by Ricardonacif** [comment]
For me when I restart the computer it doesn't work. What I have to do to make it work is: kill the unplug keyboard, kill ckb-daemon process, open ckb appllication, then plug keyboard again. I believe it has something to do with starting the MacOS with the keyboard plugged in.

**Comment by ghost** [comment]
Anyways, with the default setup after quickinstall I cannot reproduce on hackintosh on 10.13.whatever.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/49
