### ISSUE TITLE
Corsair Glaive Mouse Delay.

### ISSUE THREAD

**Issue by ruixe** [mattanger/ckb-next#369]
Hi everyone, I am new to the GitHub thing... I am unsure about the format, please pardon me about this. I am a Linux (Lubuntu 17.04) user and I need help because my mouse, Glaive RGB sometimes shows delays when I scroll the wheel. It also sometimes gives delays when I click. This made gaming very uncomfortable. I am also new to codes and stuff. Please patiently tell me what to do because I am unsure of what is going on. Thank you!

**Comment by Ravenslofty** [comment]
Sorry we missed you in IRC! We were all asleep (the dev team is mostly European).

Latency issues are very hard to fix, because ckb spends most of its time waiting for events from the kernel, which is expensive.

The lowest-latency approach is to write a kernel driver for Linux, but that's out of scope for this project.

At the moment, the driver sleeps on events from the kernel - this means the kernel has to give us a free timeslot, which has been known to be a latency problem on heavily loaded systems...such as somebody gaming.

A lower-latency approach is to constantly poll the device for packets, but this has the drawback of increased TL;DR.

Depending on how we choose to fix #367, this may or may not get fixed. But this is an unfortunate case of not being able to eat our cake and have it too.

**Comment by tatokis** [comment]
https://github.com/ckb-next/ckb-next/issues/53
