### ISSUE TITLE
Bindings only work when I have ckb-next running

### ISSUE THREAD

**Issue by yyk** [mattanger/ckb-next#386]
I added some macro bindings to my K65 LUX RGB, it works fine when the ckb-next UI is running. However if I quit the UI, the bindings doesn't work any more. Win key stopped working as well. Any idea how to fix?

**Comment by yyk** [comment]
In Debian testing.

**Comment by tatokis** [comment]
That's how it is.
You can either read the daemon manual and send the bindings after sending the active command, or sigkill the GUI after it starts, so that it doesn't set the KB back to hardware mode.

Either way, by doing so you lose any control over features such as brightness/winlock/other indicators or animations.
